baseURL: ''
languageCode: en-us
title: Yourfolio Theme
theme: yourfolio
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
googleAnalytics: UA-XXXXX-Y
menu:
  main:
    - name: About
      weight: 1
      url: /about
    - name: Contact
      weight: 2
      url: /contact
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo
themesDir: themes
publishDir: public
